version: '3'

services:
  daemon:
    build: .
    image: ulord:lastest
    container_name: ulord
    volumes:
      - ./ulordcore:/root/.ulordcore
    ports:
      - "19889:19889"
      - "19887:19887"